# -*- coding: utf-8 -*-
"""Week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GtGt0pSSWpAAodt2kVfWIX5p8DCPP4b

Loops
"""

for loop in range(1,6):
  print("Him")

grades = [35,50,65,85]

for grade in grades:
  print(grade)

grades = ['A,B,C']

for grade in grades:
  print(grade)

grades = ["35","50","65","85"]

for grade in grades:
  print(grade)

numbers = [1,2,3,4]

for number in numbers:
  print(number*number)

print(list(range(0,10)))
print(list(range(1,11,3)))
print(list(range(10,1,-1)))

for temp in range(1,11):
  print(2,"*",temp,"=",2*temp)

"""While Loop"""

inputValue=input("Enter a number greater than 10")

while int(inputValue)>10:
  print("With in range")

print("Got invalid number",inputValue)

"""Ascending order"""

for i in range(1,11):
  print(i)

"""Descending Order"""

for i in range(10,0,-1):
  print(i)

for i in range(5, 51, 5):
    print(i)

for i in range(60, 5, -6):
    print(i)

while 1==0 or 0==1:
  print("ABC")

while False:
  print("ABC")

while True:
  print("ABC")

"""Activity 1"""

number=1

  while number<=20:
    print(number)
    number=number+1

number=20

  while number>=1:
    print(number)
    number=number-1

"""Activity 2"""

number=3

  while number<=30:
    print(number)
    number+=3

number=3

  while number<=30:
    print(number)
    number+=2

number=40

  while number>=4:
    print(number)
    number-=4

"""Activity 3"""

number = int(input("Enter a Number: "))
sum=0

while number != 0:
    sum = sum + number
    print("Sum is: ",sum)
    number = int(input("Enter a Number: "))
print("The total Sum is:",sum)

"""Loop Control"""

for loop in [1,2,3,4]:
  if loop == 3:
    continue
  print(loop)
else:
  print("All the elements")

for loop in [1,2,3,4]:
  if loop == 3:
    break
  print(loop)
else:
  print("All the elements")

for loop in [1,2,3,4]:
  if loop == 3:
    continue
  print(loop)
else:
  print("All the elements")

grades = [35,50,65,85]
for grade in grades:
  print(grade)
else:
  print("Completed the grades for Loop")

"""Nested Loop"""

gradebook = [
 ['Jing', 35],
 ['Jim', 50],
 ['Kerrie', 65],
 ['Rakesh', 85]
]

for student in gradebook:
 print(student)
 for detail in student:
 print(details)

for outerloop in range(1,10):
  for innerloop in range(0,outerloop):
    print("*",end="")
  print()

for outerloop in range(10,0,-1):
  for innerloop in range(0,outerloop):
    print("*",end="")
  print()

"""List Comprehensions"""

alist = [loop for loop in range(1,11)]
print(alist)

alist = [loop for loop in range(1,11) if int(loop%2)==0]
print(alist)

alist = [loop*loop for loop in range(1,11)]
print(alist)

alist = [loop*loop/10 for loop in range(1,11)]
print(alist)

alist = [word for word in ["sara","sunny","him"] if "a" in word]
print(alist)

"""Calculator"""

from ast import operator
for i in range(time):
  print(Calculation(i+1))

  num1 = int(input("Enter first number: "))
  num2 = int(input("Enter second number: "))
  operator = input("Enter operator (+, -, *, /): ")

  if operator == "+":
    print("Result:", num1 + num2)
  elif operator == "-":
    print("Result:", num1 - num2)
  elif operator == "*":
    print("Result:", num1 * num2)
  elif operator == "/":
    print("Result:", num1 / num2)
  else:
    print("Invalid operator.")

"""Calculator"""

while True:
  value1 = int(input("Enter first number: "))
  value2 = int(input("Enter second number: "))
  operator = input("Operator or q to quit: ")
  if operator == "+":
    print(value1 + value2)
  elif operator == "-":
    print(value1 - value2)
  elif operator == "*":
    print(value1 * value2)
  elif operator == "/":
    print(value1 / value2)
  elif operator == "q":
    break
  else:
    print("Invalid operator")