# -*- coding: utf-8 -*-
"""Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_w4_mUvPrcUyPmcPK92MPQzSD919ENp
"""

student_name = ["nav", "sah", "ek"]
print(student_name)
print(student_name[0])

sports = ["Basketball", "soccer", "tennis", "crickets"]
print(sports[0])
print(sports[3])
print(sports)

list = ["Criketer", "Footballer", "Vollyball", "Basketball", "Tennisball", "Badminton", "Skating", "Hockey"]
print(list)
# print(list[0])
# print(list[1])
# print(list[2])
# print(list[3])
# print(list[4])
# print(list[5])
# print(list[6])
# print(list[7])
for avariable in list:
  print(avariable)

list = "student"
print(len(list))

grades = [35, 56, 67, 78]
grades.remove(35)
print(grades)
grades.pop(0)
print(grades)
del grades[0]
print(grades)

gradebook = [
    ['Jing',35],
    ['Kim',50],
    ['Kerrie',65],
    ['Rakesh',85],
]
print(gradebook[0][1])
print(gradebook[-4][1])
print(gradebook[-4][-1])
print(gradebook[0][-1])

students = ['Jing', 'Jim']
grades = [35, 50]
gradebook = builtins.list(zip(students, grades))
print(gradebook)

list =[1,2,3,4,5,6,7,8,9]
print(list[0:3])
print(list)

list = [0, 1, 2, 3, 4, 5, 6, 7, 8]
print(list[-6:-2])

grade_set = {35, 50, 65, 85, 85, 85}
print(grade_set)

gradebook_dict = {
    'a': 35,
    'b': 50,
    'c': 65,
}
print(gradebook_dict)
gradebook_dict["c"] = 90
print(gradebook_dict)

grade = [35, 50, 65, 85]
print(grade)
grade.append(90)
print(grade)
print(grade[0:3])
print(grade[1:3])
print(grade[:3])
print(grade[1:])