# -*- coding: utf-8 -*-
"""Week 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjtB-I9UxCjQSG4umG5uVjct9mUV8ABs
"""

def printMenue():
  print("1. Add")
  print("2. Substraction")

printMenue()

def afuntionwithparameter(orderid):
  order ={
      'order1' :"10pm",
      'order2' : "11pm",
  }



  print(order[orderid])
afuntionwithparameter(orderid='order2')

def print_hello():
  print('1 Welcome to print_hello function')
#print_hello()

print('2 This code is outside of the print_hello function '
      'and will be always printed regardless whether '
      'print_hello function is called or not')

def getproduct(a=2,b=1):
  print(a)
  print(b)
  print(a*b)

getproduct(a=1,b=2)

def getproduct(a=2,b=1):
  a=4
  b=5
  print(a)
  print(b)
  print(a*b)

getproduct(a=1,b=2)

def print_hello(name, surname):
 print('Welcome ' + name + ' ' + surname + ' to print_hello function')
# prints Welcome Mark Smith to print_hello function
print_hello('Mark', 'Smith')
# OR print_hello(name = 'Mark', surname = 'Smith')
# OR print_hello(surname = 'Smith', name = 'Mark')

def display_grading_system(grade_type):
    print("HD: 85 - 100")
    print("D: 70 - 84")
    print("C: 50 - 69")
    print("P: 35 - 49")
    print("F: Below 35")

display_grading_system('grade')

def assign_grade(score_str):
    score = int(score_str)
    if score >= 85:
        grade = "HD"
    elif score >= 70:
        grade = "D"
    elif score >= 50:
        grade = "C"
    elif score >= 35:
        grade = "P"
    else:
        grade = "F"
    print('The student scored ' + score_str  + ', which is a grade ' + grade + '.')

assign_grade('90')
assign_grade('65')
assign_grade('45')
assign_grade('30')

def display_grading_system():
  print("HD: 85 - 100")
  print("D: 70 - 84")
  print("C: 50 - 69")

  def assign_grade(score):
    if score >= 85 and score<=100:
      grade = "HD"
    elif score >= 70 and score<=84:
      grade = "D"
    elif score >= 50 and score<=69:
      grade = "C"
    elif score >= 35:
        grade = "P"
    else:
        grade = "F"
    print('The student scored ' + score  + ', which is a grade ' + grade + '.')
assign_grade('90')
assign_grade('65')
assign_grade('45')
assign_grade('30')

def factorial():
  if n==1:
  return 1
else:
  print("Calling",n,"")

def factorial(n):
  product=1
  for loop in range(1,1+n):
    product = product*loop
  print("Factorial",product)
factorial(5)

def assign_grade(score, extra_credit=0):
  final_score = score + extra_credit


  if 85 <= final_score <= 100:
      grade = "HD"
  elif 70 <= final_score <= 84:
      grade = "D"
  elif 50 <= final_score <= 69:
      grade = "C"
  elif 35 <= final_score <= 49:
      grade = "P"
  else:
      grade = "F"


  print(f"The student scored {score}, with {extra_credit} extra credit, resulting in a final score of {final_score}, which is a grade {grade}.")

assign_grade(90, 5)