# -*- coding: utf-8 -*-
"""Week11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgjRqkxOqu0xLmZclN-MHAckzX_ant38
"""

from os import register_at_fork
class car:
  def _init_(self,color,rego,model) -> None:
    self.color = color
    self.__rego = rego
    self.model = model

  def _str_(self) -> str:
    return "Color: "+self.color


car1 = car("Red", "1","S","1998")
car2 = car("Red", "1","S","1998")
car1.rego = 10
print(car1.rego)

class car:
  color = "red"
  rego = "1234"
  def _init_(self,color) -> None:
    self.color=color
    pass

# car1 = car()
# print(car1.color)
# print(car1.rego)

class Car:
    def __init__(self, regNo):
        self.__regNo = regNo

    def setRegNo(self, regNo):
        self.__regNo = regNo

    def getRegNo(self):
        return self.__regNo

car1 = Car("MH12AB1234")

car1.setRegNo("DL09XY5678")

print("Updated Car Registration Number is:", car1.getRegNo())

class Car:
    def __init__(self, regNo):
        self.__regNo = regNo

    def getRegNo(self):
        return self.__regNo
car1 = Car("MH12AB1234")
car2 = Car("MH12AB1235")
print("Car Registration Number is:", car1.getRegNo())
print("Car Registration Number is:", car2.getRegNo())

class point:
  def __init__(self,x,y) -> None:
    self.x = x
    self.y = y
  def _str_(self) -> str:
    return "x: "+str(self.x)+" - y: "+str(self.y)

import math
class vector:
  def __init__(self,point1,point2) -> None:
    self.point1 = point1
    self.point2 = point2
  def __str_(self) -> str:
    return "start" + str(print(self.point1)) - "end" + str(print(self.point2))

  def calculate_distance(self):
    return math.sqrt((self.point2.x - self.point1.x)**2 + (self.point2.y - self.point1.y)**2)
point1 = point(0,0)
point2 = point(0,1)
vector1 = vector(point1,point2)
print(vector1.calculate_distance())

  # point(point1)
  # point(point2)