# -*- coding: utf-8 -*-
"""Week9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIjPjkLH4LQgyYvnqcRLNM7EsE6qNV85
"""

thisdict = {
    "Name":"Him Modh",
    "DOB":17/7/2004,
    "Age":21,
    "Gender":"Male"
}
print(thisdict)

tickets={
    "1":{
        "Ticket number":1,
        "Priority":"High",
        "Status":"R"
    },
    "2":{
        "Ticket number":2,
        "Priority":"Low",
        "Status":"R"
    }
}
print(tickets["1"]["Status"])
print(tickets["2"]["Priority"])

dictionary = {'Japan':10}
dictionary.update({'Australia': 10, 'Japan': 9, 'France': 8})
print(dictionary)

numbers=[number*number for number in range(1,6)]
print(numbers)

numbers={number:number for number in range(1,6)}
print(numbers)
print(list(numbers.keys()))
print(list(numbers.values()))
if 0 in numbers:
    print("Yes")
else:
    print("No")

students = ['Jing', 'Jim', 'Kerrie', 'Rakesh']
grades = [35, 50, 65, 85]
gradebook = {key:value for key, value in zip(students, grades)}
print(gradebook)

numbers={number:number*number for number in range(1,6)}
try:
  a=[1,2]
  a[5]
  numbers[0]
except KeyError:
  print("Key not found")
except IndexError:
  print("Index not found")

numbers={number:number*number for number in range(1,6)}

for key in numbers.values():
  print(key)

numbers={number:number*number for number in range(1,6)}

for key in numbers.keys():
  print(key)